name: Build and Test

inputs:
  python_version:
    description: 'Python version'
    required: true
    default: '3.10'
  architecture:
    description: 'Target architecture'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.architecture }}
        args: --release --out dist --find-interpreter
        manylinux: auto
    - name: pytest
      shell: bash
      run: |
        set -e
        pip install hydrogr --find-links dist --force-reinstall
        pip install pytest
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: hydrogr-${{ github.job }}-${{ inputs.architecture }}-${{ github.run_id }}
        path: dist
    

