name: Build and publish release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/build_all.yml

  publish-pypi:
    name: Publish to Pypi
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *

  publish-github:
    permissions:
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write
      # Used to upload release artifacts.
      contents: write
    name: Publish to GitHub releases
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/download-artifact@v4
      - name: Sigstore Sign
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./*.whl
          upload-signing-artifacts: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.whl
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
